load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_toolchain", "system_python_bootstrap_toolchain")

system_python_toolchain(
    name = "python",
    interpreter = ".venv/bin/python3",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    interpreter = ".venv/bin/python3",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)


remote_execution_properties = {
    "OSFamily": "Linux",
    # Do NOT change this to "podman://". 
    # "docker://" is the standard protocol identifier for OCI images in RBE.
    "container-image": "docker://ubuntu:20.04", 
},